-- 통합 리스크 마스터 테이블 (Layer 03: Risk Scoring)
CREATE TABLE ib.T_IB_RISK_MASTER (
    DEAL_ID VARCHAR(20) PRIMARY KEY,
    TOTAL_SCORE NUMERIC(5, 2),
    FINAL_GRADE VARCHAR(5),
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ib.T_IB_RISK_MASTER IS '통합 리스크 마스터 정보';
COMMENT ON COLUMN ib.T_IB_RISK_MASTER.DEAL_ID IS '딜 식별자';
COMMENT ON COLUMN ib.T_IB_RISK_MASTER.TOTAL_SCORE IS '최종 합산 리스크 점수 (0-100)';
COMMENT ON COLUMN ib.T_IB_RISK_MASTER.FINAL_GRADE IS '최종 등급 (AAA~D)';

-- 리스크 상세 팩터 테이블
CREATE TABLE ib.T_IB_RISK_DETAIL (
    DETAIL_ID SERIAL PRIMARY KEY,
    DEAL_ID VARCHAR(20),
    CATEGORY VARCHAR(20), -- FINANCIAL, LEGAL, OPERATIONAL, SECURITY
    FACTOR_NAME VARCHAR(50),
    RAW_VALUE NUMERIC,
    WEIGHTED_SCORE NUMERIC(5, 2),
    CONSTRAINT FK_RISK_MASTER FOREIGN KEY (DEAL_ID) REFERENCES ib.T_IB_RISK_MASTER(DEAL_ID)
);

COMMENT ON TABLE ib.T_IB_RISK_DETAIL IS '통합 리스크 상세 팩터 정보';
COMMENT ON COLUMN ib.T_IB_RISK_DETAIL.CATEGORY IS '리스크 카테고리 (FINANCIAL, LEGAL, OPERATIONAL, SECURITY)';
COMMENT ON COLUMN ib.T_IB_RISK_DETAIL.WEIGHTED_SCORE IS '가중치 반영 점수';
